platform :ios, "11.2"

target 'WalletInjector' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalletInjector
  pod 'SwiftLint'

  target 'WalletInjectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalletInjectorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
